[package]
name = "starknet_cairo_101"
version = "0.1.0"
description = "Workshop to learn the basics of Cairo."
homepage = "https://github.com/starknet-edu/starknet-cairo-101"

[[target.starknet-contract]]
name = "contracts"

# [[target.starknet-contract]]
# name = "utils/ex00_base"